/**
 * @file WarningCodes.ts
 * @description
 *
 * @author Tom Glastonbury <t@tg73.net>
 * @license MIT
 * @copyright 2024
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 * USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * Codes used with `onWarning` callbacks.
 */
export enum WarningCodes {
	HEURISTIC_SMELL = 'HEURISTIC_SMELL',
	INVALID_METADATA = 'INVALID_METADATA',
	UNKNOWN_GCODE_GENERATOR = 'UNKNOWN_GCODE_GENERATOR',
	UNSUPPORTED_SLICER_VERSION = 'UNSUPPORTED_SLICER_VERSION',
}
