; processed by RatOS.PostProcessor 1.0.0 on 2024-11-07 at 15:08:23 UTC v:2 m:999
; generated by PrusaSlicer 2.8.0+win64 on 2024-10-31 at 03:31:15 UTC                             

;
; thumbnail begin 64x64 2920
; iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAIVElEQVR4AeVby3ITRxTtnwhQFXZZJm
; GXTbJIkZgfAKzX6C1btmxJlvUyVVQwIpZkUaxZQhUbPoHPa+Zc+Y7vtHoekkeyZRbXkufR3efcc2/f
; bs2o58+fa7ZUKqXTqbR+8eIFmeM4utls6lKppF++fOkdl4bj8hzuT6fT3jF8ZrIZvbu7610bx1K7KV
; /b6Uxap9KpwH6loa92q60v/r/QlUqFjgHfbmqXMPL/MIU/5s35fF7X63V91DgiMDbAUZbJZObmgred
; b7X+1p8+/USG71YS4BC3f7QjCQ0zOVY48PzNue73+zqXy3ng2YgAkz10dnh4SASggbgdywHgM5vLUq
; esBhDLNpn8qr99Uz7DMXkNk5jNZr02ljHGUywUiYBXr17RdxOvj4BqtapbzRYNHI2gY3wPk68cMHsN
; 4PkY/geQMPBsUANfB+C4l/vAd27TJCrI0Ab6Bg6EwmQ80Z2Tjo8gIgCNHx8fk+e5UwkQjcjjcgByEA
; COTs3zsMvL3wOBm3Z6+q+1L85RtvblOGxjhuWyOf3mvzd69HZE4yQCisWiG4MtSnQ2Rj05pl05ZrIL
; XuDvAM9ekgOGhXk9yHAP328CtZHA40WylIqz5ZXmcVNPx1N9eHCoFSRvxlgQwyRvIU0vTq8kzwNma7
; efLg1c2ufPD6gNs10iwR2zSQTLPUohMCT68cVYK1tcRRkyOyU5JzefnowBrur1OGqQBgJ4toE6w8Db
; yMD1Ks7FphRBgJN3vCxvDgyeSwp8lBqgSEp26YxVKVGmgi4Magxe5zDgAXDCSdLrUWoA8RI41QsWEs
; LIwHHFAGyg5c34BHhUY9whG9pYJssnoQauD9h4rGEkSDzADDyKE4r0qskaFzUmcNh0+tvGgJt2cvJ0
; YTxMQhgRFDZXs5byedidJ1nO0utIdGZHtw2eDWOwjY1LaF/SRGF3FcJeCJjs8LSGi1AK27wO5teR6G
; 4SEjY1MAlQA5xLSduYtRYIwE2YI2FmnN0Vry+jBhDg5BwyUxELBOAGeJ1vBmM81eHmuwxeqoELIngd
; eNiRfJyx+ghAbFC8WxiczZ7ceeCmdbs7c2dmLCEhlKDI63nHY0detC1eDzKMXWIxiUAlqRDrNuCdzj
; 9bBTbIEBLAYiMC35UJnO38/O5k+Zva+/cPrBhpLRBEwMnJAz0cKv3163aBlfbhg3I3eZQul+0EkAKw
; CYKVlDyIrMkEwD5+3C7gEjwTwCW/iVNNp1PaL0Mu4IMmAbDJZDvU8OWL0mdn1+AlAZKEfCGvW+2WVt
; gHHI1G+uLiQtdqtUACtkEN0utBBMCAs9fvzQnAgUKhoHu9noYauqddmj+DCGA1bAt4SQBwHR0d6d6g
; p/fr+1TyK2YFFd/BwYGeTqb63eiduzH5KJAAtrsQEmHAPQIqD10Syrpz2nGnxI7GPijjVlIaIKFcKe
; vXr1+79kskAbcdEnHAw/b2f9bDsyHtegOjxLxAANgpl8p60H8ci4DbSJBIdHGAs9Xrj/X+/r6u1qrB
; BGAWgEyuk+DD2ARsUg1xvS6t4oYAOdiZO5hXukQANjgxJSARSiWsQsC61bAK+HkSfOitbCnp5wtkRA
; DAS+BsqxKwDjWsCtxGAJOApTKUoLj4kRckQUBS0+VNwdsIkHlAmSeSJOAmIZEE8DAC2KwEzAuhZAhY
; JSSSBM8EAJNNBQrJYBMExFGDrY5fFwEc9gonMAMgITD4dREQpoakvW4jgElACcwbv14I0NRQKKxVAU
; EJcp3gbQrAzGfNAWCE1bBuAtjWCdxMgozPmgSZIVyEaqnTeaSH94SASuWRLhVLmvOdVMPCLACGYJ3O
; /VEASmEZ4oHTIMt/Ezlg0yHASRBPii0ogGLDZYgvus8E8KzHalA8Hcgp8L4TIIlQLAfz5I9AgBcCtp
; M/FAE2EqrVnY2QsAkCCoWdYAJkRrRd1Gg82VoCSqUnVkxstCtsMmJehAQJNWwbAQDPU7rN85QEi4Xr
; HBA0G9Dc6VaGyJjrCIl1eZ33/mzgud5Z2BBhEuSFsiF8Jh0S6/Q6jf+q8PGOuV7nZ6CspTAvGNikOt
; hqtWeJlcpJAEepWyw+Wxinr/Apzs3c/rMuhhi8bMRsPCk1JOX1IPC8FV4sFX3L/cDlsFwr2xq0qeG2
; CIgCzytb9jqrYUEBTsCukAk6TA2rLp9XAd48/svLTTaj/FW8SnS57ILXObS9tYA8EDRnhpFQ26u5YI
; Z6MPxz7QTU63/oy8tLetYfP+2bY8MnXv4Iqm18uc5dACop+bCCyEYEiGs0Gu5G5hm9XgevLJsgl0l0
; 3DeA4wfc2eVMt9ttbzz4aS8OeN+mqO1HkTACmAR0hs7xXAEGtGqCXDXWQTb65ydc4AgcCxu/dVvcPB
; hFAjrf29vT3W6XBoC3scISZJQaosDbpjc2KBDvO43ejegpl4P6QeDYbRiJADqZjUcCv2CF9/BAAmIo
; 70QnyDA1LJvhpUGFSHb4hBKRG5CL5HQXBp6eEqPGnLwOUgI3hOdq+oO+Pu2eUpzJxhm4LVdcx+1ObA
; LCwLMjKtWKb9bCdzzhMh6PKUHWqrVAPPx7KO5R/EXOBGZtgOdqBsOBbhw1FoCS5cJnCllamyFhAkfp
; CoAmiVzUwOMc6zaVQg1IykiQeBxGYuIfRH1rAfnTuKwFYGgMHscTVYh1DCBOgvRVYhhk3vGV1TIkbH
; W8uQaRIRiVo6TTEBJvz996zz7AUdyG9REZGOQN4JATGERDkpS4s4RMVDbV8IYLdmtsGxZ8r6+OF0VN
; VKLD/3Aa3hSdTCb0SrB8DDCQAHSE7A4Z8QvUy84Uck1hDZmYRtNdaV7Hh7UTlr/omUA3Qc5mMz3oD+
; h6ifc7FXkmB8gX2noAAAAASUVORK5CYII=
; thumbnail end
;

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.45mm
; first layer extrusion width = 0.45mm

M73 P0 R13
;TYPE:Custom
START_PRINT EXTRUDER_TEMP=250,250 EXTRUDER_OTHER_LAYER_TEMP=250,250 BED_TEMP=first_layer_bed_temperature START_CHAMBER_TEMP=0,0 CHAMBER_TEMP=0,0 INITIAL_TOOL=0 TOTAL_LAYER_COUNT=150 X0=135 Y0=135 X1=165 Y1=165 FIRST_X=163.961 FIRST_Y=163.961 MIN_X=135.225 MAX_X=164.775 USED_TOOLS=0                                                                                                                                                                                 
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

;snip for unit test

G1 X149.783 Y163.627 E.57774
G1 X150.358 Y163.627 E.01752
G1 X136.373 Y149.642 E.60251
G1 X136.373 Y149.066 E.01755
G1 X150.934 Y163.627 E.62732
G1 X151.51 Y163.627 E.01755
G1 X136.373 Y148.49 E.65214
G1 X136.373 Y147.915 E.01752
G1 X152.085 Y163.627 E.67691
G1 X152.661 Y163.627 E.01755
G1 X136.373 Y147.339 E.70173
G1 X136.373 Y146.763 E.01755
G1 X153.237 Y163.627 E.72654
G1 X153.812 Y163.627 E.01752
G1 X136.373 Y146.188 E.75131
G1 X136.373 Y145.612 E.01755
G1 X154.388 Y163.627 E.77613
G1 X154.964 Y163.627 E.01755
G1 X136.373 Y145.036 E.80095
G1 X136.373 Y144.46 E.01755
G1 X155.54 Y163.627 E.82576
G1 X156.115 Y163.627 E.01752
G1 X136.373 Y143.885 E.85053
G1 X136.373 Y143.309 E.01755
G1 X156.691 Y163.627 E.87535
G1 X157.267 Y163.627 E.01755
G1 X136.373 Y142.733 E.90016
G1 X136.373 Y142.158 E.01752
G1 X157.842 Y163.627 E.92494
G1 X158.418 Y163.627 E.01755
G1 X136.373 Y141.582 E.94975
G1 X136.373 Y141.006 E.01755
G1 X158.994 Y163.627 E.97457
G1 X159.569 Y163.627 E.01752
G1 X136.373 Y140.431 E.99934
G1 X136.373 Y139.855 E.01755
G1 X160.145 Y163.627 E1.02416
G1 X160.721 Y163.627 E.01755
G1 X136.373 Y139.279 E1.04897
G1 X136.373 Y138.703 E.01755
G1 X161.297 Y163.627 E1.07379
G1 X161.872 Y163.627 E.01752
G1 X136.373 Y138.128 E1.09856
G1 X136.373 Y137.552 E.01755
G1 X162.448 Y163.627 E1.12337
G1 X163.024 Y163.627 E.01755
G1 X136.373 Y136.976 E1.14819
G1 X136.373 Y136.401 E.01752
G1 X163.599 Y163.627 E1.17296
G1 X163.627 Y163.079 E.01672
G1 X136.921 Y136.373 E1.15056
G1 X137.497 Y136.373 E.01755
G1 X163.627 Y162.503 E1.12574
G1 X163.627 Y161.928 E.01752
G1 X138.072 Y136.373 E1.10097
G1 X138.648 Y136.373 E.01755
G1 X163.627 Y161.352 E1.07616
G1 X163.627 Y160.776 E.01755
G1 X139.224 Y136.373 E1.05134
G1 X139.799 Y136.373 E.01752
G1 X163.627 Y160.201 E1.02657
G1 X163.627 Y159.625 E.01755
G1 X140.375 Y136.373 E1.00175
G1 X140.951 Y136.373 E.01755
G1 X163.627 Y159.049 E.97694
G1 X163.627 Y158.473 E.01755
G1 X141.527 Y136.373 E.95212
G1 X142.102 Y136.373 E.01752
G1 X163.627 Y157.898 E.92735
G1 X163.627 Y157.322 E.01755
G1 X142.678 Y136.373 E.90253
G1 X143.254 Y136.373 E.01755
G1 X163.627 Y156.746 E.87772
G1 X163.627 Y156.171 E.01752
G1 X143.829 Y136.373 E.85295
G1 X144.405 Y136.373 E.01755
G1 X163.627 Y155.595 E.82813
G1 X163.627 Y155.019 E.01755
G1 X144.981 Y136.373 E.80332
G1 X145.556 Y136.373 E.01752
G1 X163.627 Y154.444 E.77854
G1 X163.627 Y153.868 E.01755
G1 X146.132 Y136.373 E.75373
G1 X146.708 Y136.373 E.01755
G1 X163.627 Y153.292 E.72891
G1 X163.627 Y152.717 E.01752
G1 X147.283 Y136.373 E.70414
G1 X147.859 Y136.373 E.01755
G1 X163.627 Y152.141 E.67932
G1 X163.627 Y151.565 E.01755
G1 X148.435 Y136.373 E.65451
G1 X149.011 Y136.373 E.01755
G1 X163.627 Y150.989 E.62969
G1 X163.627 Y150.414 E.01752
G1 X149.586 Y136.373 E.60492
G1 X150.162 Y136.373 E.01755
G1 X163.627 Y149.838 E.58011
G1 X163.627 Y149.262 E.01755
G1 X150.738 Y136.373 E.55529
G1 X151.313 Y136.373 E.01752
G1 X163.627 Y148.687 E.53052
G1 X163.627 Y148.111 E.01755
G1 X151.889 Y136.373 E.5057
G1 X152.465 Y136.373 E.01755
G1 X163.627 Y147.535 E.48089
G1 X163.627 Y146.96 E.01752
G1 X153.04 Y136.373 E.45611
G1 X153.616 Y136.373 E.01755
G1 X163.627 Y146.384 E.4313
G1 X163.627 Y145.808 E.01755
G1 X154.192 Y136.373 E.40648
G1 X154.768 Y136.373 E.01755
G1 X163.627 Y145.232 E.38167
G1 X163.627 Y144.657 E.01752
G1 X155.343 Y136.373 E.35689
G1 X155.919 Y136.373 E.01755
G1 X163.627 Y144.081 E.33208
G1 X163.627 Y143.505 E.01755
G1 X156.495 Y136.373 E.30726
G1 X157.07 Y136.373 E.01752
G1 X163.627 Y142.93 E.28249
G1 X163.627 Y142.354 E.01755
G1 X157.646 Y136.373 E.25768
G1 X158.222 Y136.373 E.01755
G1 X163.627 Y141.778 E.23286
G1 X163.627 Y141.203 E.01752
G1 X158.797 Y136.373 E.20809
G1 X159.373 Y136.373 E.01755
G1 X163.627 Y140.627 E.18327
G1 X163.627 Y140.051 E.01755
G1 X159.949 Y136.373 E.15846
G1 X160.525 Y136.373 E.01755
G1 X163.627 Y139.475 E.13364
G1 X163.627 Y138.9 E.01752
G1 X161.1 Y136.373 E.10887
G1 X161.676 Y136.373 E.01755
G1 X163.627 Y138.324 E.08405
G1 X163.627 Y137.748 E.01755
G1 X162.252 Y136.373 E.05924
G1 X162.827 Y136.373 E.01752
G1 X163.627 Y137.173 E.03447
G1 X163.609 Y136.391 E.02383
;WIDTH:0.581236
G1 X163.626 Y136.456 E.00271
G1 X163.579 Y136.504 E.00271
G1 X163.514 Y136.486 E.00272
G1 X163.496 Y136.421 E.00272
G1 X163.544 Y136.374 E.00271
;LAYER_CHANGE
;Z:30
;HEIGHT:0.200001
;BEFORE_LAYER_CHANGE
;30

;WIPE_START
G1 F24000
G1 X163.496 Y136.421 E-.01915
G1 X163.514 Y136.486 E-.01922
G1 X163.579 Y136.504 E-.01922
G1 X163.626 Y136.456 E-.01915
G1 X163.609 Y136.391 E-.01915
G1 X163.627 Y137.173 E-.22293
G1 X162.827 Y136.373 E-.32244
G1 X162.252 Y136.373 E-.16387
G1 X163.627 Y137.748 E-.55419
G1 X163.627 Y138.324 E-.16416
G1 X162.445 Y137.142 E-.47652
;WIPE_END
G1 Z30 F12000
;AFTER_LAYER_CHANGE
;30
G92 E0
_ON_LAYER_CHANGE LAYER=150
G1 Z31
G1 X164.775 Y164.775 F30000
G1 Z30 F12000
G1 E2 F7200
M204 S10000
;TYPE:External perimeter
;WIDTH:0.449999
G1 F18000
G1 X135.225 Y164.775 E.90021
G1 X135.225 Y135.225 E.90021
G1 X164.775 Y135.225 E.90021
G1 X164.775 Y150 E.4501
G1 X164.775 Y164.715 E.44828
M204 S15000
G1 X163.795 Y164.624 F30000
M73 P97 R0
M204 S3000
;TYPE:Top solid infill
;WIDTH:0.453034
G1 F6000
G1 X164.441 Y163.978 E.02804
G1 X164.441 Y163.398 E.0178
G1 X163.398 Y164.441 E.04527
G1 X162.818 Y164.441 E.0178
G1 X164.441 Y162.818 E.07044
G1 X164.441 Y162.238 E.0178
G1 X162.238 Y164.441 E.09562
G1 X161.658 Y164.441 E.0178
G1 X164.441 Y161.658 E.12079
G1 X164.441 Y161.078 E.0178
G1 X161.078 Y164.441 E.14597
G1 X160.498 Y164.441 E.0178
G1 X164.441 Y160.498 E.17114
G1 X164.441 Y159.918 E.0178
G1 X159.918 Y164.441 E.19631
G1 X159.338 Y164.441 E.0178
G1 X164.441 Y159.338 E.22149
G1 X164.441 Y158.758 E.0178
G1 X158.758 Y164.441 E.24666
G1 X158.178 Y164.441 E.0178
G1 X164.441 Y158.178 E.27184
G1 X164.441 Y157.598 E.0178
G1 X157.598 Y164.441 E.29701
G1 X157.018 Y164.441 E.0178
G1 X164.441 Y157.018 E.32219
G1 X164.441 Y156.438 E.0178
G1 X156.438 Y164.441 E.34736
G1 X155.858 Y164.441 E.0178
G1 X164.441 Y155.858 E.37253
G1 X164.441 Y155.278 E.0178
G1 X155.278 Y164.441 E.39771
G1 X154.698 Y164.441 E.0178
G1 X164.441 Y154.698 E.42288
G1 X164.441 Y154.118 E.0178
G1 X154.118 Y164.441 E.44806
G1 X153.538 Y164.441 E.0178
G1 X164.441 Y153.538 E.47323
G1 X164.441 Y152.958 E.0178
G1 X152.958 Y164.441 E.4984
G1 X152.378 Y164.441 E.0178
G1 X164.441 Y152.378 E.52358
G1 X164.441 Y151.798 E.0178
G1 X151.798 Y164.441 E.54875
G1 X151.218 Y164.441 E.0178
G1 X164.441 Y151.218 E.57393
G1 X164.441 Y150.638 E.0178
G1 X150.638 Y164.441 E.5991
G1 X150.058 Y164.441 E.0178
G1 X164.441 Y150.058 E.62427
G1 X164.441 Y149.479 E.01777
G1 X149.479 Y164.441 E.64941
G1 X148.899 Y164.441 E.0178
G1 X164.441 Y148.899 E.67458
G1 X164.441 Y148.319 E.0178
G1 X148.319 Y164.441 E.69975
G1 X147.739 Y164.441 E.0178
G1 X164.441 Y147.739 E.72493
G1 X164.441 Y147.159 E.0178
G1 X147.159 Y164.441 E.7501
G1 X146.579 Y164.441 E.0178
G1 X164.441 Y146.579 E.77528
G1 X164.441 Y145.999 E.0178
G1 X145.999 Y164.441 E.80045
G1 X145.419 Y164.441 E.0178
G1 X164.441 Y145.419 E.82562
G1 X164.441 Y144.839 E.0178
G1 X144.839 Y164.441 E.8508
G1 X144.259 Y164.441 E.0178
G1 X164.441 Y144.259 E.87597
G1 X164.441 Y143.679 E.0178
G1 X143.679 Y164.441 E.90115
G1 X143.099 Y164.441 E.0178
G1 X164.441 Y143.099 E.92632
G1 X164.441 Y142.519 E.0178
G1 X142.519 Y164.441 E.95149
G1 X141.939 Y164.441 E.0178
G1 X164.441 Y141.939 E.97667
G1 X164.441 Y141.359 E.0178
G1 X141.359 Y164.441 E1.00184
G1 X140.779 Y164.441 E.0178
M73 P98 R0
G1 X164.441 Y140.779 E1.02702
G1 X164.441 Y140.199 E.0178
G1 X140.199 Y164.441 E1.05219
G1 X139.619 Y164.441 E.0178
G1 X164.441 Y139.619 E1.07736
G1 X164.441 Y139.039 E.0178
G1 X139.039 Y164.441 E1.10254
G1 X138.459 Y164.441 E.0178
G1 X164.441 Y138.459 E1.12771
G1 X164.441 Y137.879 E.0178
G1 X137.879 Y164.441 E1.15289
G1 X137.299 Y164.441 E.0178
G1 X164.441 Y137.299 E1.17806
G1 X164.441 Y136.719 E.0178
G1 X136.719 Y164.441 E1.20324
G1 X136.139 Y164.441 E.0178
G1 X164.441 Y136.139 E1.22841
G1 X164.441 Y135.559 E.0178
G1 X135.559 Y164.441 E1.25358
G1 X135.559 Y163.861 E.0178
G1 X163.861 Y135.559 E1.22841
G1 X163.281 Y135.559 E.0178
G1 X135.559 Y163.281 E1.20324
G1 X135.559 Y162.701 E.0178
G1 X162.701 Y135.559 E1.17806
G1 X162.121 Y135.559 E.0178
G1 X135.559 Y162.121 E1.15289
G1 X135.559 Y161.541 E.0178
G1 X161.541 Y135.559 E1.12771
G1 X160.961 Y135.559 E.0178
G1 X135.559 Y160.961 E1.10254
G1 X135.559 Y160.381 E.0178
G1 X160.381 Y135.559 E1.07736
G1 X159.801 Y135.559 E.0178
G1 X135.559 Y159.801 E1.05219
G1 X135.559 Y159.221 E.0178
G1 X159.221 Y135.559 E1.02702
G1 X158.641 Y135.559 E.0178
G1 X135.559 Y158.641 E1.00184
G1 X135.559 Y158.061 E.0178
M73 P99 R0
G1 X158.061 Y135.559 E.97667
G1 X157.481 Y135.559 E.0178
G1 X135.559 Y157.481 E.95149
G1 X135.559 Y156.901 E.0178
G1 X156.901 Y135.559 E.92632
G1 X156.321 Y135.559 E.0178
G1 X135.559 Y156.321 E.90115
G1 X135.559 Y155.741 E.0178
G1 X155.741 Y135.559 E.87597
G1 X155.161 Y135.559 E.0178
G1 X135.559 Y155.161 E.8508
G1 X135.559 Y154.581 E.0178
G1 X154.581 Y135.559 E.82562
G1 X154.001 Y135.559 E.0178
G1 X135.559 Y154.001 E.80045
G1 X135.559 Y153.421 E.0178
G1 X153.421 Y135.559 E.77528
G1 X152.841 Y135.559 E.0178
G1 X135.559 Y152.841 E.7501
G1 X135.559 Y152.261 E.0178
G1 X152.261 Y135.559 E.72493
G1 X151.681 Y135.559 E.0178
G1 X135.559 Y151.681 E.69975
G1 X135.559 Y151.101 E.0178
G1 X151.101 Y135.559 E.67458
G1 X150.521 Y135.559 E.0178
G1 X135.559 Y150.521 E.64941
G1 X135.559 Y149.941 E.0178
G1 X149.941 Y135.559 E.62423
G1 X149.361 Y135.559 E.0178
G1 X135.559 Y149.361 E.59906
G1 X135.559 Y148.781 E.0178
G1 X148.781 Y135.559 E.57388
G1 X148.201 Y135.559 E.0178
G1 X135.559 Y148.201 E.54871
G1 X135.559 Y147.621 E.0178
G1 X147.621 Y135.559 E.52353
G1 X147.042 Y135.559 E.01777
G1 X135.559 Y147.042 E.4984
G1 X135.559 Y146.462 E.0178
G1 X146.462 Y135.559 E.47323
G1 X145.882 Y135.559 E.0178
G1 X135.559 Y145.882 E.44806
G1 X135.559 Y145.302 E.0178
G1 X145.302 Y135.559 E.42288
G1 X144.722 Y135.559 E.0178
G1 X135.559 Y144.722 E.39771
G1 X135.559 Y144.142 E.0178
G1 X144.142 Y135.559 E.37253
G1 X143.562 Y135.559 E.0178
G1 X135.559 Y143.562 E.34736
G1 X135.559 Y142.982 E.0178
G1 X142.982 Y135.559 E.32219
G1 X142.402 Y135.559 E.0178
G1 X135.559 Y142.402 E.29701
G1 X135.559 Y141.822 E.0178
G1 X141.822 Y135.559 E.27184
G1 X141.242 Y135.559 E.0178
G1 X135.559 Y141.242 E.24666
G1 X135.559 Y140.662 E.0178
G1 X140.662 Y135.559 E.22149
G1 X140.082 Y135.559 E.0178
G1 X135.559 Y140.082 E.19631
G1 X135.559 Y139.502 E.0178
G1 X139.502 Y135.559 E.17114
G1 X138.922 Y135.559 E.0178
G1 X135.559 Y138.922 E.14597
G1 X135.559 Y138.342 E.0178
G1 X138.342 Y135.559 E.12079
G1 X137.762 Y135.559 E.0178
G1 X135.559 Y137.762 E.09562
G1 X135.559 Y137.182 E.0178
G1 X137.182 Y135.559 E.07044
G1 X136.602 Y135.559 E.0178
G1 X135.559 Y136.602 E.04527
G1 X135.559 Y136.022 E.0178
G1 X136.205 Y135.376 E.02804
M204 S15000
;WIPE_START
G1 F24000;_WIPE
G1 X135.559 Y136.022 E-.26037
G1 X135.559 Y136.602 E-.1653
G1 X136.602 Y135.559 E-.42038
G1 X137.182 Y135.559 E-.1653
G1 X135.559 Y137.182 E-.65415
G1 X135.559 Y137.762 E-.1653
G1 X135.979 Y137.342 E-.1692
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
; Filament-specific end gcode
END_PRINT
M73 P100 R0
; objects_info = {"objects":[]}
; filament used [mm] = 3385.84, 0.00
; filament used [cm3] = 8.14, 0.00
; filament used [g] = 10.34, 0.00
; filament cost = 0.38, 0.00
; total filament used [g] = 10.34
; total filament cost = 0.38
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 13m 55s
; estimated first layer printing time (normal mode) = 1m 52s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 0
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = C:\\Users\\Helge\\AppData\\Roaming\\PrusaSlicer\\printer\\ratrig-vcore-bed-300x300.stl
; bed_custom_texture = C:\\Users\\Helge\\AppData\\Roaming\\PrusaSlicer\\printer\\Bed-Texture-300x300 - no logo.svg
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 85,85
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\n
; between_objects_gcode = ;BETWEEN_OBJECTS\nG92 E0
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0
; bridge_acceleration = 2500
; bridge_angle = 0
; bridge_fan_speed = 50,50
; bridge_flow_ratio = 0.7
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0,0
; chamber_temperature = 0,0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 0,0
; cooling_tube_length = 0
; cooling_tube_retraction = 0
; default_acceleration = 15000
; default_filament_profile = "Generic PLA @RatRig"
; default_print_profile = 0.20mm NORMAL @RatRig
; deretract_speed = 120,120
; disable_fan_first_layers = 0,0
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0,0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode";"; Filament-specific end gcode"
; end_gcode = END_PRINT\n
; external_perimeter_acceleration = 10000
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 300
; external_perimeters_first = 0
; extra_loading_move = 0
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = #DFDF00;#0000A0
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.9,0.9
; extrusion_width = 0.45
; fan_always_on = 1,1
; fan_below_layer_time = 5,5
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 2,2
; filament_cooling_initial_speed = 3,3
; filament_cooling_moves = 0,0
; filament_cost = 36.29,36.29
; filament_density = 1.27,1.27
; filament_deretract_speed = nil,nil
; filament_diameter = 1.75,1.75
; filament_infill_max_crossing_speed = 0,0
; filament_infill_max_speed = 0,0
; filament_load_time = 0,0
; filament_loading_speed = 14,14
; filament_loading_speed_start = 19,19
; filament_max_volumetric_speed = 0,0
; filament_minimal_purge_on_wipe_tower = 10,10
; filament_multitool_ramming = 0,0
; filament_multitool_ramming_flow = 10,10
; filament_multitool_ramming_volume = 10,10
; filament_notes = CHAMBER_TEMP=50;CHAMBER_TEMP=50
; filament_purge_multiplier = 100%,100%
; filament_ramming_parameters = "10 10| 0.05 2.66451 0.45 3.05805 0.95 4.05807 1.45 5.97742 1.95 7.69999 2.45 8.1936 2.95 11.342 3.45 11.4065 3.95 7.6 4.45 7.6 4.95 7.6";"10 10| 0.05 2.66451 0.45 3.05805 0.95 4.05807 1.45 5.97742 1.95 7.69999 2.45 8.1936 2.95 11.342 3.45 11.4065 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil,nil
; filament_retract_before_wipe = nil,nil
; filament_retract_layer_change = 1,1
; filament_retract_length = 2,2
; filament_retract_length_toolchange = nil,nil
; filament_retract_lift = 1,1
; filament_retract_lift_above = nil,nil
; filament_retract_lift_below = nil,nil
; filament_retract_restart_extra = nil,nil
; filament_retract_restart_extra_toolchange = nil,nil
; filament_retract_speed = nil,nil
; filament_settings_id = "Prusament PETG @V-IDEX";"Prusament PETG @V-IDEX"
; filament_shrinkage_compensation_xy = 0%,0%
; filament_shrinkage_compensation_z = 0%,0%
; filament_soluble = 0,0
; filament_spool_weight = 201,201
; filament_stamping_distance = 0,0
; filament_stamping_loading_speed = 20,20
; filament_toolchange_delay = 0,0
; filament_travel_lift_before_obstacle = nil,nil
; filament_travel_max_lift = nil,nil
; filament_travel_ramping_lift = nil,nil
; filament_travel_slope = nil,nil
; filament_type = PETG;PETG
; filament_unload_time = 0,0
; filament_unloading_speed = 20,20
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; filament_wipe = 1,1
; fill_angle = 45
; fill_density = 20%
; fill_pattern = adaptivecubic
; first_layer_acceleration = 2500
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 85,85
; first_layer_extrusion_width = 0.45
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 250,250
; full_fan_speed_layer = 1,1
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 200
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil,nil
; infill_acceleration = 15000
; infill_anchor = 600%
; infill_anchor_max = 2
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 18%
; infill_speed = 300
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nG92 E0\n_ON_LAYER_CHANGE LAYER={layer_num + 1}
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000
; machine_max_acceleration_extruding = 50000
; machine_max_acceleration_retracting = 50000
; machine_max_acceleration_travel = 9000,1250
; machine_max_acceleration_x = 50000
; machine_max_acceleration_y = 50000
; machine_max_acceleration_z = 1200
; machine_max_feedrate_e = 120
; machine_max_feedrate_x = 1000
; machine_max_feedrate_y = 1000
; machine_max_feedrate_z = 100
; machine_max_jerk_e = 5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 50,50
; max_layer_height = 0.3,0.3
; max_print_height = 300
; max_print_speed = 1000
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 50
; min_bead_width = 85%
; min_fan_speed = 50,50
; min_feature_size = 25%
; min_layer_height = 0.05,0.05
; min_print_speed = 20,20
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 0
; notes = 
; nozzle_diameter = 0.4,0.4
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{print_time}.gcode
; overhang_fan_speed_0 = 0,0
; overhang_fan_speed_1 = 0,0
; overhang_fan_speed_2 = 0,0
; overhang_fan_speed_3 = 0,0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 0
; pause_print_gcode = M601
; perimeter_acceleration = 15000
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 300
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 0.2mm Prusament PETG @V-IDEX
; printer_model = 
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_RatRig\nPRINTER_MODEL_VCORE\nPRINTER_HAS_Directextruder\nE3DV6
; printer_settings_id = VC-300 IDEX
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1,1
; retract_before_wipe = 0%,0%
; retract_layer_change = 1,1
; retract_length = 0.8,0.8
; retract_length_toolchange = 0,0
; retract_lift = 0.2,0.2
; retract_lift_above = 0.2,0.2
; retract_lift_below = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 120,120
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 10
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 2,2
; small_perimeter_speed = 100
; solid_infill_acceleration = 15000
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 300
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\nSET_PRESSURE_ADVANCE ADVANCE=0.04";"; Filament gcode\nSET_PRESSURE_ADVANCE ADVANCE=0.04"
; start_gcode = START_PRINT EXTRUDER_TEMP={first_layer_temperature[0]},{first_layer_temperature[1]} EXTRUDER_OTHER_LAYER_TEMP={temperature[0]},{temperature[1]} BED_TEMP=first_layer_bed_temperature START_CHAMBER_TEMP={chamber_minimal_temperature[0]},{chamber_minimal_temperature[1]} CHAMBER_TEMP={chamber_temperature[0]},{chamber_temperature[1]} INITIAL_TOOL={initial_tool} TOTAL_LAYER_COUNT={total_layer_count} X0={first_layer_print_min[0]} Y0={first_layer_print_min[1]} X1={first_layer_print_max[0]} Y1={first_layer_print_max[1]}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 2
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 2
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 65
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 250,250
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; thumbnails = 64x64/PNG, 400x300/PNG
; thumbnails_format = PNG
; toolchange_gcode = T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.45
; top_one_perimeter_type = top
; top_solid_infill_acceleration = 3000
; top_solid_infill_speed = 100
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_acceleration = 15000
; travel_lift_before_obstacle = 0,0
; travel_max_lift = 0,0
; travel_ramping_lift = 0,0
; travel_slope = 0,0
; travel_speed = 500
; travel_speed_z = 200
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 15000
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 0
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 10
; wipe_tower_x = 144.414
; wipe_tower_y = 187.751
; wiping_volumes_matrix = 0,0,0,0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
; TESTING COMMENT: this is not a valid ratos_meta block - but this does not matter, V2 files are rejected outright.
; ratos_meta begin 999
; h6ifc7FXkmB8gX2noAAAAASUVORK5CYII=
; ratos_meta end 1