; generated by PrusaSlicer 2.8.0+win64 on 2024-11-07 at 15:11:49 UTC


;
; thumbnail begin 160x120 8728
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAZWUlEQVR4Ae2dCZBVVXrHXxVTk8qYsV
; Kp1Dgaq2ZilVWTMaYmZTRaqUrGUZMalcWF7qah9x2a3hsa2UFBWQUEBYVmHRumlQEEAwYHCMrIFpVF
; RBBk35F9seRL/w5zum7ffve9e++79y3Nteqv8njvvnfO+Z9vP98JpaWliRVycnLk1VdflUGDBkl6er
; ot1NbWyowZM6SkpKT1tYyMDE/Ro0cPVygoKJDXX39dhg4dKpmZmbY+09DQIG+99ZYUFha2+zuekSjw
; /UVFRTJ//nwZOHCg9OzZM+pYXnrpJTl8+LBcuXJFFi9eHHZMbhDLWoasyFddXS1Tp05Vg7RLPg2IO2
; 3aNBkyZEjMPzBW0mn069dP3nzzTSkrK3P82dzcXLWp2IgsdCKJp8EmmjVrlhQXF7cjZiSUlpbK2rVr
; 5dq1a7Jz504ZMGCA7c3oBxHbEZAf88orr6jdwkOdks8o8ZgkSJyXl5cw4mVlZcnEiRPVmHr16hX1/Z
; EWfeTIkWpjQchEES87O1tJ5NGjR6ux2ZWW5jEyjrNnz8q5c+cUkREaXpDQCRHhRRsCojYhTEVFhSvi
; hVO3PBPpUVdXF1figb59+yqpV1NT44pw4YAEbWxsVM+MN/mYQ1Qu43L7DOPYGcPnn38u169flw0bNq
; h1jxcJ6+vrZceOHTcJCHGQVhMmTFBSwgvimck0ZswY9Xx2rZ+k06QaNWqUvPbaa2qXxUI4KzCW116s
; kz7Zz/hGOCMmTZokkydP9lz6IlEXLlwoly5dkqNHj6px2bEn3RKRZyPBkb7Hjx+XEAvEwDC2vSaeGd
; iVSKQ+ffr4QjyAzTp9+nRlmOsd7wchxuQ+KFvLOrXgB/JqwYO+fAfo3bu3LFiwQNmwftqfCKD9+/cr
; 2/D9999XtqWX68I6s+4ff/xxq8QtLy+XEFIC79Bv8mmw46ZMmaLsKS93GoB0kA+179dC5fV8XuYX3C
; OflYXa4Pcl90hBrzRPvws7fObMmcpb9Ws8RrB5V61apUi4Z88eR9GCaBg3bpySsNicjElrwhD/igfx
; zBIPsrzxxhuehAIwoCE1C4YJ4dcCDcx+VNaV3NaOfBobyn4kQ3Ifi/l7ULPYmSNGjLDtaHgJnLaTJ0
; /KhQsXlPQ1mzFOwPouX75chX6++OIL6d+/f1svOBHkM6pLHBRCAW4HWFVVpWwKDGi/FiQ7M13mFNxr
; STwzZhffJzk9M1x91wsvvCBz585VqjfexDMCR2fTpk3y3XffydatW1V81+naELb66quv5PLlyyrumJ
; +f30YlOyKgl8QzA4cBI5udb3dwSLqxY8eqQDkS0LeF6PV0RKlnhVVld0hN9lPqGZgaVtDfw/8TGmE8
; iQzzGIH0ZTOcP39eTp06pZw6Xou2NphZeOuoWwLfrG8PC7sw5Df57BIKCYZtUFlZafkePTGEQnBmcJ
; z8mnykHo7GlhZHwyn5NHBQJhU+FJGAgLGzYIRF2FjRyBpvoKF2796tbMPVq1cr6Wy1Rqzf5s2blaOx
; Zs2aqIH/UKKJZwS7C0n48ssvtwkaGydj2LBhynZEffs14WW9usqyop+4Jp4Zy0t+qsI14UiFFMcMwR
; GMRtREkhL1uWzZMrl69aocOHBA2du8blwj7HBsxzNnzqiUp53AfyhZyGcEhioSjrSRngCdxx0+fLhv
; E89zh+X8hyuVGw2byv5ChuY/3kocNtC8efNUupKN54Z8iSAkGSW8Wey65uZmtS5EHZCMSMjPPvvMkb
; 0Y8pJ8sRLPuJsYGCEVFkjncYkjeU04DZyGBYX3eE48M+YX/0JeGtogs2fPVgvnFfHiSUhU8Pr165Wa
; 3bVrlxw8eFAuXrwoTU1Njj3mULJIPbOqBUiGd955R7nx5qS7F6TTqM5+0hepZ4VPKv5G+hd28518fh
; IRAbFt2za5ceOG8M/KlSsdOZHtCJhMxANEyZF65D+RfCTMyR96RTot9Sbn/ypuxGvjoPT+gUwr+pe4
; ktArMrImkA+VS2UNVTVIQ6Qi4RvHBEw28r344osqJIHhq1/DoCVPOX78eOXmuyWdRt+szi2Oxh0JIZ
; 8RK0t/YumgJBsRWQOEAk4GzgYhI7WRW8Jg2IPkk48cOaIcK163RcBEkS/cADHM8XCx+6wmiN1H4NnK
; HrQz8WPzHpKNpT9MOPlapWFLqGd8wcMJIaFdIjLf2u7buHGjCreY30PmBg8ZTxmP2U4+2TEB/SAeIA
; Ng9nytgKFL2Rj5ZJ16szPR8XI03IJ8cmFWetIRkUomJBuB5Tlz5kQM/ONYffjhh0o9EzscPHiwet0T
; AvpBPgZDNQ6xP6d5T5LlOiYYbXIH5TwaV0fDLdaX/ViG5D2WMBIaiUged+nSpSrkApl0hZEdsKZkT8
; iikE2xclBC8SCf1Y/UeVz+64R4xslCYiI5idZbSb1p+fcnPfHMIJ8cKSviNyAbpKOIAHXqJvCPmiaP
; TD6ZvDLr3I6AGPTxJh8DJKDptMDSarJYKJ5HFgX1rF/H0Xi/+G9TinhGkE+uzOkaV+KhkZBYqFsCzq
; jfSOo5GuAXFTVU1pw4cUKtkTFDEiLYS6FovFQuEovUEzaf3YHZnTzGQT65prJcORqx5HGTBXbzyV4A
; iYWDcf3PIRVCYbGQzwgkKjWG2IbUHMIDRUDsLooFYTpv9FPl4t1CeCdBZaeTWJH3vGwY9M8pRTI7WF
; z6cynN6e4L8ZBISCYkFKXymDRILuN7vCAhwesVK1YoL5nqa7zmVhuQ/B3k0Mz0knzE84jrGb1Wr4kH
; UsXRcAudT2YOvbIP8VqRSJBi+/btraX/VvCCiAi8Y8eOqfRdGycE+4mKBipOvCIfxMbRsHuSy80kJn
; t4xWuQT87NymwlolsyUtixb98+FUDWhQV2PucFCYkrci4kZLb5tKpEYjlJLJu/ANVO1sJu5sIt+XA0
; OrLUswLhmrrcp9uQ0C4R0UiLFi1SjgGBYzJPTknsBQl5TsjK5kMVo5LJvzqVerAbqYc4d/JjnEq9iX
; kPdAhHwy3IJ08p+td2JIxEJjQSJVPG4lI3G98rEoYiORwMhAAxh1TCFReGeyCGJdITce6n1EuGPG6y
; gHxyec6zEYmIRiJof/r06Tbl9W7J5xkB7ahXAoh4RrjlVuQjas4AyU7Y/XFuBj0695GkyuMmC3BQhh
; U8EZaEaKR169ap8MqWLVtU6X8sxPOShLYICAgY46pjL5gfwtkMCGr3JJebgd5qjoZbNJXcK4XZ6a3k
; Q4MdOnSo9Ygl9p9X5POChLYJqEEAGduQ1AzOBSU5ZCHs5nHdDLAh+/Fb0tFwCxyUkWVdZMmSJSqPu3
; fvXuVY+pnaiwsB9YcIJLObqFZ20qTHjdRLxTxusuBgU18V+CXW58ZbTioCGklEazDyuGRPiBvaOZfr
; dECpnsdNFpBPjuagJJKEISfkYyfpxj/6C3ULNPKwXpGvo+RxkwU6n5yMJAzZJR9tFnTrXfNDkICEas
; JVTjj58fm9uktT4c9SanFTCc0l90hRdoavJPScgGRDiBnZafxD4BmS6qpmJz+8o+dxkwV/KvtRm3xy
; oqVgRALqfn5OGv8QDyQQTT7Zzo/F0XDS+CeAN5hTfF+bfHJSEVDZYWPHKrXqpvEPAyLRzbmNSHGnWz
; WPmyxYU/bXUmvIJyeChO0IqBv/0B7DKfHMapfANCqZfLJZ6gWORnIAB2WyIZ+cUAKiNum/4rYjZ1gV
; 2yJBkaac6SVw3TurW5DHTUIsL7lThWviRUA0I0kMRUD+APG03eYV+YygCmPRK6WByk1iqHxy/hO+k5
; DkBXUDhPBCqEcneVw3BAzyuKkFCl4LstI8JyAakLQtFdG6RjSEeoy1D3GkHxHkcVMT5JP75/7WMwIi
; 4NCy5hrRUKTavljIF+RxUx+xNlDS/MC0I5YczrcIxUI+KwIGBaMdC7rg1SkBqZjSZ4ysbMKQ19IvCK
; 90TBCucdJACVWLyo3WVDTkFfnI4waORsdHtAZKpG45iGa3RtQTAgZ53FsLVg2USNkSXqGFnuaILwQ0
; Ohoz8u9LqckL4B10AyUkHUc1zL15fCUgjsYfS25PqQkL4D0oeJ01fnDrZd7RYoExEzDI4wYwg3AN+W
; TfCcgFLn8ouiulJidA/BDuQh7PCBjtpsgAAYBqoJT3uHcE5M60cPfjBggQCTqfHBMB3d4UGSAAIFxT
; k/OUcwIi9Sbc4o1/AngDHJSphQ/YJyBSz8ubIgMEADcv5OnWnoDGxpHcjxs0/gngF3BQRub/pi0BVW
; +X0S/J3PzA0QgQHzQV/b30yrxZBBPSlQvTCn8l/5ufWgMJkHpYlxeSAc/+UlXKkLZrtQE5FzKhX5Ys
; z/urlBpQgNTA1pKQ/K57Jynq+rDiG80LuDO5jRNCYnlgTW9pLPql/KkwtQYYIHnxUUFIRnS5U7LSut
; oLw3A2eFr/dPmfnNQaaIDkw9KenaSiy/3OA9GcWhpanS8L8+6QzSWpNegAiQcqd1K32yXnuf+MLRVX
; U1Uhb1Y9IR/mptYEBEgcVmaFpPbpe6Vnj/TYc8G6zHp0VYa8m/3jlJqIAPEFUq/x+b+UvK7/HpV4jg
; gIcFAaasqlsfj+wEEJ0A6EV0Z0uSuso+EJATXoDz25PkOWZwcZkwA3sTCtk5R0echW+VXMBAQ4KL+f
; N0Oay+4NHJRbGJuKbzoa2endbNf/eSIB58+fr84AVFWUyxsVjwXhmlsQy3t1kroWR6NXZoZr8jkmIL
; cgNTY2qj7R+jUusBndUCZ/KLpT/q80tSYxgHPgaEztdpvkPvu44/MfrglIjz8uH+TWHfNFxtpB6V9b
; IW8V3qei3qk0oQHsA0ej32/vbqNyYyGfLQLSvg2Vy6HjaO0YaD4zsS4zyCd3MCD1cDSKuz7i6uSbaw
; Jy0JjmMubDxpHAIeXBdeUyp/DeIFzTAYBGG9n5jrBSL1YC0pfIMhfMVVz0iXbbN7hPWYlMq3s2cFBS
; GORxa7rdH3GdY5F+YQnIfSAzZ85s08vNDQG17TiitlCa838ahGtSCDqPG87R8FL64cC2EpA/zJo1S1
; 04be5q5JaA2kGpq6mSGRW/DgpeUwB/bMn5m8MrfpCPPtEUpSoCcgXr3LlzLftEx0JADQpex9X2lKW5
; gYOSjEDqNWXeJoNK7DWidEs+BBKt22gNjYYMcasR50IiXUjjBQG1gzKgulRml/xT4KAkEXQeF0eDUF
; s0x9Mt+fAtkHq6fZuyAfX17dE+7BUJ2QGUY0+p6y7LMlNroToiCK/07vpAmzWqrKxU5lhVVZUn5ONz
; JDG44regoKDNxUghJw/xkoRI3CGVudKUf3fgoCQA2tHI7t457BqxPhAGdWlMPjglH4SjQfngwYPV58
; 03cznqjuUlATXIJ0+vfDwI18QR4fK4VhgwYIC6R0bfgOoEJDEw8VC9VhdiJoSAZhKqgtd+RSqfnEoL
; mWpA6s3qfpvkPfOoo7UiJMedf0OGDLElBZGY9InGnsTuj3Qja8IIaCahclDqqmRm0T8G+WQfgKMxtP
; NdETMaVtDrP3LkyNYbUK04QqcN+kRjP2pHwzMC+k1CwN0SE2vTgnyyR4iWx7VLPg2uXaAwRXuyRl5A
; UCIqEDQa8VwTMB4kVCfy+lfIgoKfy8ai1FrwZAKa5OWnbncl9SKpWtYIFQtYK4QGth72on5PShEwHA
; nBkIEDZOWUvoGD4gI4GrWdf2HL0XBCPiO4AbW5uVlVS1Ej6pR8rgkYDxISKT9y5IicP39emmaMlXcK
; goJXO3CSx3VLPECYBnWLozF9+nSVwtWfT1kCAsT50qVL5fLly7J7925V+o+DUl/dYtz2/rcgnxwBOB
; oqvNKju6/kq66uVhkNY2s/As04H3jMcSGgHyQcOHCgfPnll3L16lV57733lFg3SkWCmuPrgwZKZujG
; P24dDbvkYw2QeNh+FK+Y/571ImZIGV9cCOgVCRHnFEOcO3dOjh49qtSvrkMM56AMrO0tjYX/EOSTy3
; Tjn7tcOxp2yafzuOb7fs0qlz9DUl1fEIl8GRkZsRMwVhKSd9y4caNcv35d1q9fr8S6+T3hHBR1AfIt
; 3kCpOaOTlHe+31fiAQLQFChgHkUinxHEAQnXsJ4RCRjrfcFuSQiJKPk/ceKEfPvtt0p0s2OifcYI1M
; Ct2ECp1dF47r98JR/xPH3fL/Ntl3wa2O7kk0eNGqW+00w+RUAOG3lBQCckxFZYtWqVsvV27NihbAan
; 5DWCBkozbpEGSv+dbT+PG4vUI9BMbM/qvl8njgbxQTxlzpQbyacIiARCXzv5cbGQcPjw4bJv3z65dO
; mSiiHhNbndxUYSsltHVWZIc1bHbKDkNo/rlHxILWxwXQUTK/k0dD4ZR7MNAXfu3Kkk0cqVKxVD/SIh
; BQcLFy6UCxcuyMGDB9X1nm4PPFmRUeWTa8tlVgdroER4ZWTXv/M8o2FGeXm5CqVQI2r1HjfkM0o90n
; WoZcwnRUCY+e6776q429dff630vdckJGL+6aefKkdj9erVyqPyinjhwEaaVJ8hS7NSv4ESedy+ab9W
; 0gMP1A/y8T4CydjkhLq8JJ5Z5QIcSBwUHJVWJ2T06NFy6NAhuXjxojQ1NYWN8zgFUokddfr0aTl16p
; QqTERK+Uk+DdTHsIZKdSVAKjoo5sY/jGfMmDEyceLEsN0p3Eo9BBC2HqrR6nNekk+D75owYcJNAmpg
; cK5Zs0auXbumJBaSyy35kHJr165VUm/r1q0qem6lnv1ERXlvmVr+m5QK10TK4zKPOrwRC/FAQ0ODIl
; +kYlM/yNfGBgznOhNwRGoB/j+cCx4JWppi73HAHfsvEeTTQJqP6l8qi5O8gVKkxj9G4HBhR3GG2w3x
; CHchSQmPmI/gekE8u+QLS0AN3HBttyHJkGjRBob9sHjxYuXh7t27N2wFbaJIyCbqV1Mhr+fdl5T5ZB
; yN+id/JlkZz9oeE2qT8Ea4ALEVsLswi0gAJErq2SIgYKe9/fbbyi7Ec0WyRRLn2qNesWJFVI86UUTE
; 5plQ2yNp8sluC0b1PDLPEIqz3dHmG4mH3aU1UqKknm0CageF2B0eMp4yEs7oKSHCOcJHNuPYsWMqUe
; 1EJSSChPzmQXV9ZG5xYi/ksdP4JxzpzEC6o45Ry+HOdxP4x5Qi4O8H8dySzxYBNTBUiRXioCDpkHgY
; whs2bFBqmv8ay3OcIhFEVPnkhoyEOCh2Gv9EI54ZzD8pTX0eA3AckuiDlZpOFPFAenq6fQICdhpZk+
; PHjysHA6lHBQvNjKyi5slORCTG8JoCac6PTz7ZbsGo2/ljPKhZshnkcdFebvK4fpIP4mmEnH4pO+mj
; jz6S77//Xm7cuCHbtm0TL/PJiSAjBvnv5s+VxvonfXVQuMAlUh7Xq3nDgVy0aJHKPJlDLF4QzyvyOS
; Yg4nzPnj3KFqRqGQcFCejG9ksGMmILYjsh1THMcbrG1GTK0lxv88nqApfnfigFXR7xhXAajIdgNUAS
; 6sNCVCsnWuqFI59tAqJeiedxPuPw4cPKm9KDJhSwa9euVu/XSUggkWREMrA4eI/G11FXA2r7SqNHDZ
; SMjX/8nBPsWbxhc/KAMaGGsQOJhyYT+WwREIN2y5YtytEgSxKuzQKkW7JkiVy5cqU1/uc3CWMhJZsG
; r1Cf5Ar3Hv5uUu3zMV3Io8IrXR70fdzk742Nf8JJO9aNmCEETQbiRSUgg8CIPXnypMqIIC2QDlbvZy
; IQ/UhInQGJ1PItEcRkgUi4U4ljJyeN5B9ckSMLi+9x5KDoPK7Ta6ucgvHQqcCq8Y8ZWkVrc8lP4tkh
; nyIgbzR/MbufqhWdE6Y8x+5uoaRn3bp17XLAiQZjQEU5dZhYKPLJdi/kUXlcmzdFxgIqY6I1/rECa0
; J1DWo7EVKvHQE1+GLqtQ4cOKCyHzgZGOdOB4jkQNyfPXu2tQrGTwclEvgtFFeOGzcuJoms8sn1hZYN
; lHA03nzuNsl55jHfx4MEIysVrfFPJLCuqG3KsOIt9cISkAmmQhniUbGM5+R2cFqFs0sJ0yBJkahuWn
; zFAnY4UiLcSS43YBP1r62UmaYLeXA0Gp6823eVi/TWjX9iWRsjsId5JhGAeBIPqHpAPkzcaPv27Yoo
; ujI6nGp2A+wUYlIUKHzzzTfK/vJzkTRR2EBIXqsCy1jAMydUd5f3WvLJOBpFXR/2fTzMGxUsbjRSJL
; DOOp9Mqi4e5OMzSHG0Ughb4MyZM+p0GgNkwEaV7AV4Jqp9//79KoaIpLVKiMcKig30SS4/1b66kKe+
; XF59ZYRlSVMs0HMHOYyNf7wknhHMFTFROICz6ZfUI2LCGXCC/2lpaRK63uIsfPLJJyqPaPVFXg0ag/
; mDDz5QkhaJSwdNI0ljBc8jvGLV7d8PUMRLKjJSeZNT0mkQo8TL1afJ/CCeGfAAoRSJD26IB4hH6mgK
; 5FME5PZLdnC0H+bVBPDlOryDk0Ly3BzecbpwOBeIc5wNP6RRNOAYkH8lxBEL4TR04x8chEihLy+JZw
; TjQRIiEb0gH2vCOmNv8mdNPkVAp/reKyISCti8ebMK15BbRpJYvTfSIrJTkXqxHB/wCtjSlKZZ1ULa
; nRfd+CeepAsHnDdsQ9SmW6nHMxBymFxG4rkmoJdExPOeN2+eSvHRik1LELuSVHfk9OIAlVdgolEzZI
; OczAU2GKEVHS5KJPGMwDvWh5acOhqEeRgTvykc+cD/A2cRz34tUSYwAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object Shape-Box id:0 copy 0
; stop printing object Shape-Box id:0 copy 0

;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.14.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 X107.623 Y87.6229 W34.7542 H34.7542 ; mesh bed levelling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P2 R2
M73 Q2 S2

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0




M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-.8 F2100
M73 P4 R2
M73 Q4 S2
G1 Z.6 F720
G1 X108.202 Y88.752 F10800
G1 Z.2 F720
M73 P5 R2
M73 Q5 S2
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X109.235 Y87.949 E.04102
G1 X110 Y87.811 E.02437
G1 X140 Y87.811 E.94063
G1 X141.248 Y88.202 E.04101
M73 P6 R2
M73 Q6 S2
G1 X142.051 Y89.235 E.04102
G1 X142.189 Y90 E.02437
G1 X142.189 Y120 E.94063
G1 X141.798 Y121.248 E.04101
M73 P7 R2
M73 Q7 S2
G1 X140.765 Y122.051 E.04102
G1 X140 Y122.189 E.02437
G1 X110 Y122.189 E.94063
G1 X108.752 Y121.798 E.04101
M73 P8 R2
M73 Q8 S2
G1 X107.949 Y120.765 E.04102
G1 X107.811 Y120 E.02437
G1 X107.811 Y90 E.94063
M73 Q9 S2
G1 X108.184 Y88.809 E.03913
M73 P9 R2
M73 Q10 S2
M204 S1000
;WIPE_START
G1 F8640
G1 X108.202 Y88.752 E-.0138
G1 X109.235 Y87.949 E-.30211
G1 X110 Y87.811 E-.17949
G1 X111.319 Y87.811 E-.3046
;WIPE_END
G1 Z.6 F720
M73 P10 R2
; printing object Shape-Box id:0 copy 0
G1 X139.213 Y119.213 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
G1 X110.787 Y119.213 E.89128
G1 X110.787 Y90.787 E.89128
M73 P11 R2
M73 Q11 S2
G1 X139.213 Y90.787 E.89128
M73 P12 R2
M73 Q12 S2
G1 X139.213 Y105 E.44564
M73 P13 R2
M73 Q13 S2
G1 X139.213 Y119.153 E.44376
M73 P14 R2
M73 Q14 S2
M204 S1000
G1 X139.59 Y119.59 F10800
M73 P14 R1
M73 Q14 S1
M204 S800
;TYPE:External perimeter
G1 F1200
G1 X110.41 Y119.59 E.91492
G1 X110.41 Y90.41 E.91492
M73 P15 R1
M73 Q15 S1
G1 X139.59 Y90.41 E.91492
M73 P16 R1
M73 Q16 S1
G1 X139.59 Y105 E.45746
M73 P17 R1
M73 Q17 S1
G1 X139.59 Y119.53 E.45558
M73 P18 R1
M73 Q18 S1
M204 S1000
;WIPE_START
G1 F8640
G1 X139.59 Y119.59 E-.01385
G1 X136.185 Y119.59 E-.78615
M73 Q19 S1
;WIPE_END
G1 Z.6 F720
G1 X139.043 Y91.723 F10800
G1 Z.2 F720
M73 P19 R1
G1 E.8 F2100
M204 S800
;TYPE:Solid infill
;WIDTH:0.421716
G1 F1200
G1 X138.447 Y91.126 E.02657
G1 X137.911 Y91.126 E.01688
G1 X138.874 Y92.089 E.0429
G1 X138.874 Y92.624 E.01685
G1 X137.376 Y91.126 E.06673
G1 X136.84 Y91.126 E.01688
G1 X138.874 Y93.16 E.0906
G1 X138.874 Y93.696 E.01688
G1 X136.304 Y91.126 E.11448
G1 X135.769 Y91.126 E.01685
G1 X138.874 Y94.231 E.13831
M73 Q20 S1
G1 X138.874 Y94.767 E.01688
G1 X135.233 Y91.126 E.16218
G1 X134.697 Y91.126 E.01688
M73 P20 R1
G1 X138.874 Y95.303 E.18606
G1 X138.874 Y95.839 E.01688
G1 X134.161 Y91.126 E.20993
G1 X133.626 Y91.126 E.01685
G1 X138.874 Y96.374 E.23376
G1 X138.874 Y96.91 E.01688
M73 Q21 S1
G1 X133.09 Y91.126 E.25764
G1 X132.554 Y91.126 E.01688
M73 P21 R1
G1 X138.874 Y97.446 E.28151
G1 X138.874 Y97.981 E.01685
G1 X132.019 Y91.126 E.30535
G1 X131.483 Y91.126 E.01688
M73 P22 R1
M73 Q22 S1
G1 X138.874 Y98.517 E.32922
G1 X138.874 Y99.053 E.01688
G1 X130.947 Y91.126 E.3531
G1 X130.412 Y91.126 E.01685
M73 Q23 S1
G1 X138.874 Y99.588 E.37693
G1 X138.874 Y100.124 E.01688
M73 P23 R1
G1 X129.876 Y91.126 E.4008
G1 X129.34 Y91.126 E.01688
M73 Q24 S1
G1 X138.874 Y100.66 E.42468
G1 X138.874 Y101.196 E.01688
M73 P24 R1
G1 X128.804 Y91.126 E.44855
G1 X128.269 Y91.126 E.01685
M73 Q25 S1
G1 X138.874 Y101.731 E.47238
G1 X138.874 Y102.267 E.01688
M73 P25 R1
G1 X127.733 Y91.126 E.49626
G1 X127.197 Y91.126 E.01688
M73 Q26 S1
G1 X138.874 Y102.803 E.52013
M73 P26 R1
G1 X138.874 Y103.338 E.01685
G1 X126.662 Y91.126 E.54397
G1 X126.126 Y91.126 E.01688
M73 P27 R1
M73 Q27 S1
G1 X138.874 Y103.874 E.56784
G1 X138.874 Y104.41 E.01688
M73 Q28 S1
G1 X125.59 Y91.126 E.59172
G1 X125.055 Y91.126 E.01685
M73 P28 R1
G1 X138.874 Y104.945 E.61555
G1 X138.874 Y105.481 E.01688
M73 P29 R1
M73 Q29 S1
G1 X124.519 Y91.126 E.63942
G1 X123.983 Y91.126 E.01688
M73 P30 R1
M73 Q30 S1
G1 X138.874 Y106.017 E.6633
G1 X138.874 Y106.553 E.01688
M73 Q31 S1
G1 X123.447 Y91.126 E.68717
G1 X122.912 Y91.126 E.01685
M73 P31 R1
G1 X138.874 Y107.088 E.711
G1 X138.874 Y107.624 E.01688
M73 P32 R1
M73 Q32 S1
G1 X122.376 Y91.126 E.73488
G1 X121.84 Y91.126 E.01688
M73 P33 R1
M73 Q33 S1
G1 X138.874 Y108.16 E.75875
G1 X138.874 Y108.695 E.01685
M73 P34 R1
M73 Q34 S1
G1 X121.305 Y91.126 E.78258
G1 X120.769 Y91.126 E.01688
M73 P35 R1
M73 Q35 S1
G1 X138.874 Y109.231 E.80646
G1 X138.874 Y109.767 E.01688
M73 P36 R1
M73 Q36 S1
G1 X120.233 Y91.126 E.83034
G1 X119.698 Y91.126 E.01685
M73 P37 R1
M73 Q37 S1
G1 X138.874 Y110.302 E.85417
G1 X138.874 Y110.838 E.01688
M73 P38 R1
M73 Q38 S1
G1 X119.162 Y91.126 E.87804
G1 X118.626 Y91.126 E.01688
M73 P39 R1
M73 Q39 S1
G1 X138.874 Y111.374 E.90192
G1 X138.874 Y111.91 E.01688
M73 P40 R1
M73 Q40 S1
G1 X118.09 Y91.126 E.92579
G1 X117.555 Y91.126 E.01685
M73 P41 R1
M73 Q41 S1
G1 X138.874 Y112.445 E.94962
G1 X138.874 Y112.981 E.01688
M73 P42 R1
M73 Q42 S1
G1 X117.019 Y91.126 E.9735
G1 X116.483 Y91.126 E.01688
M73 P43 R1
M73 Q43 S1
G1 X138.874 Y113.517 E.99737
G1 X138.874 Y114.052 E.01685
M73 P44 R1
M73 Q44 S1
G1 X115.948 Y91.126 E1.0212
G1 X115.412 Y91.126 E.01688
M73 P45 R1
M73 Q46 S1
G1 X138.874 Y114.588 E1.04508
G1 X138.874 Y115.124 E.01688
M73 P47 R1
M73 Q47 S1
G1 X114.876 Y91.126 E1.06896
G1 X114.341 Y91.126 E.01685
M73 P48 R1
M73 Q48 S1
G1 X138.874 Y115.659 E1.09279
G1 X138.874 Y116.195 E.01688
M73 P49 R1
M73 Q49 S1
G1 X113.805 Y91.126 E1.11666
G1 X113.269 Y91.126 E.01688
M73 P50 R1
M73 Q51 S1
G1 X138.874 Y116.731 E1.14054
M73 P51 R1
G1 X138.874 Y117.267 E.01688
M73 P52 R1
M73 Q52 S1
G1 X112.733 Y91.126 E1.16441
G1 X112.198 Y91.126 E.01685
M73 P53 R1
M73 Q53 S1
G1 X138.874 Y117.802 E1.18824
G1 X138.874 Y118.338 E.01688
M73 P55 R1
M73 Q55 S1
G1 X111.662 Y91.126 E1.21212
G1 X111.126 Y91.126 E.01688
M73 P56 R1
M73 Q56 S1
G1 X138.873 Y118.874 E1.23597
G1 X138.338 Y118.874 E.01685
M73 P57 R0
M73 Q58 S0
G1 X111.126 Y91.662 E1.21212
G1 X111.126 Y92.198 E.01688
M73 P59 R0
M73 Q59 S0
G1 X137.802 Y118.874 E1.18824
G1 X137.266 Y118.874 E.01688
M73 P60 R0
M73 Q60 S0
G1 X111.126 Y92.734 E1.16437
G1 X111.126 Y93.269 E.01685
M73 P62 R0
M73 Q62 S0
G1 X136.731 Y118.874 E1.14054
G1 X136.195 Y118.874 E.01688
M73 P63 R0
M73 Q63 S0
G1 X111.126 Y93.805 E1.11666
G1 X111.126 Y94.341 E.01688
M73 P64 R0
M73 Q64 S0
G1 X135.659 Y118.874 E1.09279
G1 X135.124 Y118.874 E.01685
M73 P65 R0
M73 Q66 S0
G1 X111.126 Y94.876 E1.06896
G1 X111.126 Y95.412 E.01688
M73 P67 R0
M73 Q67 S0
G1 X134.588 Y118.874 E1.04508
G1 X134.052 Y118.874 E.01688
M73 P68 R0
M73 Q68 S0
G1 X111.126 Y95.948 E1.0212
G1 X111.126 Y96.483 E.01685
M73 P69 R0
M73 Q69 S0
G1 X133.517 Y118.874 E.99737
G1 X132.981 Y118.874 E.01688
M73 P70 R0
M73 Q70 S0
G1 X111.126 Y97.019 E.9735
G1 X111.126 Y97.555 E.01688
M73 P71 R0
M73 Q72 S0
G1 X132.445 Y118.874 E.94962
G1 X131.909 Y118.874 E.01688
M73 P73 R0
M73 Q73 S0
G1 X111.126 Y98.091 E.92575
G1 X111.126 Y98.626 E.01685
M73 P74 R0
M73 Q74 S0
G1 X131.374 Y118.874 E.90192
G1 X130.838 Y118.874 E.01688
M73 P75 R0
M73 Q75 S0
G1 X111.126 Y99.162 E.87804
G1 X111.126 Y99.698 E.01688
M73 P76 R0
M73 Q76 S0
G1 X130.302 Y118.874 E.85417
G1 X129.767 Y118.874 E.01685
M73 P77 R0
M73 Q77 S0
G1 X111.126 Y100.233 E.83034
G1 X111.126 Y100.769 E.01688
M73 P78 R0
M73 Q78 S0
G1 X129.231 Y118.874 E.80646
G1 X128.695 Y118.874 E.01688
M73 P79 R0
M73 Q79 S0
G1 X111.126 Y101.305 E.78258
G1 X111.126 Y101.84 E.01685
M73 P80 R0
M73 Q80 S0
G1 X128.16 Y118.874 E.75875
G1 X127.624 Y118.874 E.01688
M73 Q81 S0
G1 X111.126 Y102.376 E.73488
G1 X111.126 Y102.912 E.01688
M73 P81 R0
G1 X127.088 Y118.874 E.711
G1 X126.552 Y118.874 E.01688
M73 P82 R0
M73 Q82 S0
G1 X111.126 Y103.448 E.68713
G1 X111.126 Y103.983 E.01685
M73 P83 R0
M73 Q83 S0
G1 X126.017 Y118.874 E.6633
G1 X125.481 Y118.874 E.01688
M73 P84 R0
M73 Q84 S0
G1 X111.126 Y104.519 E.63942
G1 X111.126 Y105.055 E.01688
M73 P85 R0
M73 Q85 S0
G1 X124.945 Y118.874 E.61555
G1 X124.41 Y118.874 E.01685
G1 X111.126 Y105.59 E.59172
G1 X111.126 Y106.126 E.01688
M73 P86 R0
M73 Q86 S0
G1 X123.874 Y118.874 E.56784
G1 X123.338 Y118.874 E.01688
M73 P87 R0
M73 Q87 S0
G1 X111.126 Y106.662 E.54397
G1 X111.126 Y107.197 E.01685
G1 X122.803 Y118.874 E.52013
G1 X122.267 Y118.874 E.01688
M73 P88 R0
M73 Q88 S0
G1 X111.126 Y107.733 E.49626
G1 X111.126 Y108.269 E.01688
M73 Q89 S0
G1 X121.731 Y118.874 E.47238
M73 P89 R0
G1 X121.195 Y118.874 E.01688
G1 X111.126 Y108.805 E.44851
G1 X111.126 Y109.34 E.01685
M73 P90 R0
M73 Q90 S0
G1 X120.66 Y118.874 E.42468
G1 X120.124 Y118.874 E.01688
G1 X111.126 Y109.876 E.4008
G1 X111.126 Y110.412 E.01688
M73 P91 R0
M73 Q91 S0
G1 X119.588 Y118.874 E.37693
G1 X119.053 Y118.874 E.01685
G1 X111.126 Y110.947 E.3531
G1 X111.126 Y111.483 E.01688
M73 Q92 S0
G1 X118.517 Y118.874 E.32922
M73 P92 R0
G1 X117.981 Y118.874 E.01688
G1 X111.126 Y112.019 E.30535
G1 X111.126 Y112.554 E.01685
G1 X117.446 Y118.874 E.28151
G1 X116.91 Y118.874 E.01688
M73 P93 R0
M73 Q93 S0
G1 X111.126 Y113.09 E.25764
G1 X111.126 Y113.626 E.01688
G1 X116.374 Y118.874 E.23376
G1 X115.838 Y118.874 E.01688
G1 X111.126 Y114.162 E.20989
G1 X111.126 Y114.697 E.01685
M73 P94 R0
M73 Q94 S0
G1 X115.303 Y118.874 E.18606
G1 X114.767 Y118.874 E.01688
G1 X111.126 Y115.233 E.16218
G1 X111.126 Y115.769 E.01688
G1 X114.231 Y118.874 E.13831
G1 X113.696 Y118.874 E.01685
G1 X111.126 Y116.304 E.11448
G1 X111.126 Y116.84 E.01688
G1 X113.16 Y118.874 E.0906
G1 X112.624 Y118.874 E.01688
G1 X111.126 Y117.376 E.06673
G1 X111.126 Y117.911 E.01685
M73 P95 R0
M73 Q95 S0
G1 X112.089 Y118.874 E.0429
G1 X111.553 Y118.874 E.01688
G1 X110.957 Y118.277 E.02657
M204 S1000
; stop printing object Shape-Box id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
G1 X111.553 Y118.874 E-.19478
G1 X112.089 Y118.874 E-.12376
G1 X111.126 Y117.911 E-.31446
G1 X111.126 Y117.376 E-.12353
G1 X111.259 Y117.509 E-.04347
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P97 R0
M73 Q97 S0
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[{"name":"Shape-Box id:0 copy 0","polygon":[[140.000,120.000],[110.000,120.000],[110.000,90.000],[140.000,90.000]]}]}
; filament used [mm] = 98.67
; filament used [cm3] = 0.24
; filament used [g] = 0.29
; filament cost = 0.01
; total filament used [g] = 0.29
; total filament cost = 0.01
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 2m 19s
; estimated printing time (silent mode) = 2m 19s
; estimated first layer printing time (normal mode) = 2m 19s
; estimated first layer printing time (silent mode) = 2m 19s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; colorprint_heights = 
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4 and printer_model!=\"MK3.5MMU3\"";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and printer_notes!~/.*MINIIS.*/ and printer_model!=\"MK3.5\" and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_settings_id = "Generic PLA"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 12
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.27{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.035{elsif nozzle_diameter[0]==0.5}0.025{elsif nozzle_diameter[0]==0.6}0.02{elsif nozzle_diameter[0]==0.8}0.014{elsif nozzle_diameter[0]==0.25}0.12{elsif nozzle_diameter[0]==0.3}0.08{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.14.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
